# more info here https://hub.docker.com/_/mysql
#   and here https://help.pythonanywhere.com/pages/AccessingMySQLFromOutsidePythonAnywhere/
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: tryout
      MYSQL_USER: karinature
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306

#   run it:
# docker-compose up -d
# docker-compose up -d -f mysql-docker-compose.yml
#
#   connect to server
# mysql -h 127.0.0.1 -u root -P 3306 -p <MYSQL_ROOT_PASSWORD>
#
#         Hurray!!
#
#  If you Stop running containers without removing them They can be started again with
#
#   stop server
# docker-compose stop
# docker-compose stop -f mysql-docker-compose.yml
#
#   start server
# docker-compose start
# docker-compose start -f mysql-docker-compose.yml

  #  ---------------------------
# for the browser GUI
# Use <MYSQL_USER>/<MYSQL_ROOT_PASSWORD> as <MYSQL_USER>/<MYSQL_ROOT_PASSWORD> credentials
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
